apiVersion: apps/v1
kind: Deployment
metadata:
  name: spartappdep
  labels:
    app: spartapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spartapp
  template:
    metadata:
      labels:
        app: spartapp
    spec:
      containers:
      - name: spartapp
        image: ehienabs/spartapp:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: spartapp-service
  labels:
    app: spartappsvc
spec:
  selector:
    app: spartapp
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer

